site_name: graphreadability
repo_url: https://github.com/PhilipMathieu/graphreadability/

plugins:
- search
- mkdocstrings:
    default_handler: python
- privacy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

theme:
  name: "material"
  palette:
    primary: white
  font:
    text: Ovo
    code: Inconsolata
  logo: assets/logo_512.png
  favicon: assets/logo_512.png

extra:
  generator: false

nav:
- Home: index.md
- MetricsSuite: metricssuite.md
- Supported Metrics: metrics.md
- Contributing: contributing.md
- References: references.md
